language: node_js
dist: trusty
node_js:
  - '8'

addons:
  ssh_known_hosts:
    - viz.vsp.tu-berlin.de

branches:
  only:
    - master
    - staging
    - dev

# build the webapp into ./dist
# travis doesn't have the option to run different builds for different branches, so we have to
# it with ugly bash if statements
script:
  - if [ -f src/firebase-secure.js ]; then sed -i "s/{{FIREBASE_KEY}}/$FIREBASE_KEY/" src/firebase-secure.js; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build && npm run unit; fi
  - if [ "$TRAVIS_BRANCH" == "staging" ]; then npm run build-staging && npm run unit; fi
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then npm run build-dev && npm run unit; fi

# the script statement for each deploy refer to the deploy.sh script because the script tag in the deploy section
# only supports one command...
deploy:
  - on:
      branch: master
    provider: script
    script: bash deploy.sh viz
    skip_cleanup: true
  - on:
      branch: staging
    provider: script
    script: bash deploy.sh viz-staging
    skip_cleanup: true
  - on:
      branch: dev
    provider: script
    script: bash deploy.sh viz-dev
    skip_cleanup: true
env:
  global:
    secure: AFkZCl5WVx+RZA29X+BMjsujXyx9URisWAVd+Muwll52+XcwkWFY1dR0hkVXNXUktCmqezv2wvjOS1d1rdmYUc02R95eHricVXJNJj2XIVP6u61qHTLAX6aJrIE486cuYT8rf/5F2JsElwhY7kCon27MIyQPoqIWF+5a2bY2tMNyd2PQqwT/V5aBu+m35g0YqOgXKiO3kBPPi8S8ZkQJhvAHYaV91MI0RiL3t62K+SHSFHhajSNuWO5i4dQzEgMsTZqQK1LAcNQJwIt7WOI7r7+j1az9QxJalI15xhIw3VxX21pfYKgpBqtF1IcPC4vjYpfdchwQQAXchs93ZJHz+fmsLHWhy/lJKbaVevKHF7klZmycY0iWonp2kVSH6UpIFFl70LkmTJZjPb17LgHv4BZBc/05l0nnrorgPWviWlAPYCAH1O5UQq9bA8w7pInrs/3KOBkwgcmMdRTZEkhCtV0A0o5mxKZcF9lHnXzhdGBqr2BKE/DyUGzklGQm6SBhpDQtWefgDVM+UP9HCED0Ov/vGrhMbK8dxs8my8wDrbVU7tGnCQYF/kzLcVa9Oi+2gEi4qz7gNknMppv92Y6ta4CUQ8zs6U16knn7DBA6oKvOY/bgKZg/QfbUmwRt1q+0XSP4Q2hrJSoVKMs+Smk2+nAeS0CKLIALn2p8ckbnjKw=
