language: node_js
dist: trusty
node_js:
- '8'
#env:
# global:
# include $HOME for aws command
#- PATH=$HOME/.local/bin:$PATH
# provide secret keys, so that awscli understands them
#- travis encrypt AWS_ACCESS_KEY_ID=$S3_KEY_ID --add
#- travis encrypt AWS_SECRET_ACCESS_KEY=$S3_KEY --add

# build the webapp into ./dist
script: npm run build && npm run unit

# install awscli command line tool to sync files to s3
# before_deploy: pip install --user awscli

# trust these hosts
addons:
  ssh_known_hosts:
  - viz.vsp.tu-berlin.de
  - viz-dev.vsp.tu-berlin.de

# see https://github.com/travis-ci/travis-ci/issues/4006
before_deploy:
  script: sed -i '/dist/d' $TRAVIS_BUILD_DIR/.gitignore

deploy:
  on:
    branch: dev
  provider: script
  script: bash deploy.sh
    # switch to script file because deploy part supports one command only
skip_cleanup: true
