language: node_js
dist: trusty
node_js:
  - '8'

addons:
  ssh_known_hosts:
    - viz.vsp.tu-berlin.de

branches:
  only:
    - master
    - staging
    - dev

# build the webapp into ./dist
# travis doesn't have the option to run different builds for different branches, so we have to
# it with ugly bash if statements
script:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then npm run build && npm run unit; fi
  - if [ "$TRAVIS_BRANCH" == "staging"]; then npm run build-staging && npm run unit; fi
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then npm run build-dev && npm run unit; fi

deploy:
  - on:
      branch: master
    provider: script
    script: bash deploy.sh viz
    skip_cleanup: true
  - on:
      branch: staging
    provider: script
    script: bash deploy.sh viz-staging
    skip_cleanup: true
  - on:
      branch: dev
    provider: script
    script: bash deploy.sh viz-dev
    skip_cleanup: true
