language: node_js
node_js:
  - "8"
script: npm run build

deploy:
  on:
    branch: feature/#9-deployment
  provider: s3
  access_key_id: $S3_KEY_ID
  access_key: $S3_KEY
  bucket: matsim-viz-website
  local_dir: build
  skip_cleanup: true