language: node_js
dist: trusty
node_js:
- '8'
script: npm run build && npm run unit
deploy:
  on:
    branch: dev
  provider: script
  script:
  - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
  - eval "$(ssh-agent -s)"
  - ssh-add <(echo "$VSP_SSH_KEY")
  - ssh vizdeploy@viz.vsp.tu-berlin.de 'sudo rm -r /var/www/viz-dev/*'
  - scp ./dist vizdeploy@viz.vsp.tu-berlin.de:/var/www/viz-dev
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_c5f74b728438_key -iv $encrypted_c5f74b728438_iv
  -in VSP_SSH_KEY.enc -out VSP_SSH_KEY -d
