# --- Setup
title:            sonar
tagline:          'work-in-progress'
description:      '[ work-in-progress ]'
url:              http://matviz.surge.sh
baseurl:          /
version:          0.0.2

author:
  name:           'Billy Charlton'
  url:            https://gitlab.tubit.tu-berlin.de/billyc

# --- Permalinks
permalink:        pretty
relative_permalinks: false

github:
  repo:           https://gitlab.tubit.tu-berlin.de/billyc/matsim-viz

# --- Build settings
source: src
destination: build
exclude: ['node_modules']
gems: []
